### ISSUE TITLE
Maintainer Needed

### ISSUE THREAD

**Issue by DavertMik** [Codeception/VisualCeption#12]
I have released the new version of VisualCeption today. But I won't have opportunity to 
maintain it. Are you interested to become a maintainer for this package? 

If you are using this package and want to see it improved, go ahead and join the Codeception Team!

Nothing really special: merge pull requests, answer issues, and make releases when needed.

@RayRom @buresmi7

**Comment by buresmi7** [comment]
I'm interested to maintain package, but I have no experience with maintenance of opensource project. We use this package every day in our company, so I want to improve this package.

**Comment by DavertMik** [comment]
@RayRom already has write permissions. I can give them to @buresmi7 so we can have like 2 maintainers, which would be really cool.

So what maintainers should do:

* track/respond to issues 
* review/merge pull requests
* improve the project, add features / fix bugs
* release a new version when it is needed
* maintain the [changelog](https://github.com/Codeception/VisualCeption/blob/master/CHANGELOG.md)
* update documentation to track new changes. 

When there are few maintainers a flow should be like this:
* each feature should be made as PR to repo (avoid pushing to master)
* each feature should be reviewed by another maintainer

Does it sound ok?

**Comment by DavertMik** [comment]
About the current project status. I released 0.9.0 because I'm not so sure about how stable it is.
Let's test it, and if everything looks good, this can be turned to be 1.0 - a stable version which is expected to be widely.

So a few notes about release process:

* 1.0 should be delivered pretty fast, once you fix all minor bugs introduced in 0.9 and you think everything works as expected
* New versions can be made just by clicking "Draft a new release" button at the https://github.com/Codeception/VisualCeption/releases It's pretty easy. 
* Each version release notes should be added into changelog
* Small bugfixes should go to 1.0.x
* Minor features should be tagged as 1.x
* Major breaks go with X.0.0

**Comment by RayRom** [comment]
Hard when you don't know English, through the translator such hogwash turns out :(

**Comment by DavertMik** [comment]
> Hard when you don't know English, through the translator such hogwash turns out :(

Ok, no problems, PHP is a new English )

**Comment by DavertMik** [comment]
We had a discussion with @RayRom and I think we have cleared the responsibilities.

@buresmi7 you are responsible for making a new releases and updating readme and changelog. 

@RayRom and @buresmi7,  have write access to the repository, but any new feature (except minor docs fixes) should be proposed as Pull Request. Ask there for a review before merging (if reviewer doesn't appear, you can ping me, or merge)

**Comment by buresmi7** [comment]
Ok, thanks :)
