### ISSUE TITLE
VisualCeption Module

### ISSUE THREAD

**Issue by angelariggs** [Codeception/VisualCeption#2]
How do I install the VisualCeption module, and where should it go in my Codeception directory? I don't see it on Packagist, and this repo doesn't include the download / install instructions.

**Comment by buresmi7** [comment]
To install via composer (or Packagist) is needed composer.json in the project folder. The repository is not supported this now.

**Comment by buresmi7** [comment]
Module on packagist: https://packagist.org/packages/codeception/visualception
Issue is solved.
