### ISSUE TITLE
If cest file contain namespace, visualception not working

### ISSUE THREAD

**Issue by rebas82** [Codeception/VisualCeption#23]
I have in my cest file used:
```
<?php
namespace Acceptance\work;

use AcceptanceTester;
```

And visual ception have problem. I must create folders  Acceptance\work\  in first and second folder for compaire. Right now are created screenshots. But, not working compaire.

When i delete namespace, visualception working good.

**Comment by buresmi7** [comment]
What version did you try? I testet it and on latest master, VisualCeption comparation is working. The created file is: "Acceptance\Work\Test_test.png". It si file name on Linux system. Maybe it not working on Windows machine. Could you describe more details about system and libraries versions?

**Comment by rebas82** [comment]
yes, i use windows 10 64bit with PHP 5.6.30 (xampp).
