### ISSUE TITLE
Elements outside of viewport are not captured.

### ISSUE THREAD

**Issue by mpgo13** [Codeception/VisualCeption#24]
Elements that are initially outside of the users viewport are not captured, which is fine, although when scrolling to the element, so the element becomes visible in the current viewport, they are still not captured:

Steps to reproduce:

1. Create element which is initially outside of the viewport
2. Scroll to element and make it visible
3. Capture screenshot for comparison

Expected result: Expected Image should contain visible element
Actual result: Expected Image is empty or has wrong content.

**Comment by mpgo13** [comment]
This happens primarily on Firefox as reported in issue https://github.com/DigitalProducts/codeception-module-visualception/issues/47

**Comment by buresmi7** [comment]
I would like to merge w/o-jQuery branch in the near future. Could you please try this without jQuery?

**Comment by mpgo13** [comment]
This seemed to be fixed with the w/o-jQuery branch :)
