### ISSUE TITLE
Module not activated error when Using WPWebdriver instead of Webdriver

### ISSUE THREAD

**Issue by devanonyme** [Codeception/VisualCeption#35]
Hello,

I get this error when I use  WPWebdriver.
[ConfigurationException] VisualCeption uses the WebDriver. Please ensure that this module is activated.  

I want to use visual regression testing for our Wordpress site (platform using a custom plugin and theme) so I prefer to build the test around WBWebdriver.

WBWebdriver inherit from WebDriver so  I would think this should not be difficult to change.

I'll look in the code to see how it works but I would welcome any pointers.

**Comment by devanonyme** [comment]
I did a first run using webdriver works really fine!

**Comment by devanonyme** [comment]
Sorry, I missed that it was documented on front page : WebDriver module This tool only works with the webdriver module in Codeception at the moment.

You can close.

**Comment by mklepaczewski** [comment]
Maybe someone is going to find this helpful - here's my dirty workaround mklepaczewski/VisualCeption@fda245464f4ed7ded2ae51228cc1dcae7615339d . Basically the idea is to find either WebDriver module or any module that inherits from it - which WpWebDriver does.
