### ISSUE TITLE
[Error] Call to a member function executeScript() on null

### ISSUE THREAD

**Issue by cyberhorse** [Codeception/VisualCeption#36]
I get the error in the title the first time I run a VisualCeption method - dontSeeVisualChanges. 
It looks like the webDriver variable isn't getting initialised.

From the debug log:

```
Scenario Steps:

3. $I->dontSeeVisualChanges("patient_registration") ...

#1  Codeception\Module\VisualCeption->dontSeeVisualChanges
```

No images get generated in the output folder.

**Comment by RayRom** [comment]
You did not specify the second papametr area of comparing, if you compare all page that specify the tag 'body':
```$I->dontSeeVisualChanges("patient_registration", 'body'];```

**Comment by cyberhorse** [comment]
I thought it defaults to 'body' if it's not specified (as per https://github.com/Codeception/VisualCeption/blob/master/module/VisualCeption.php#L291)

Also it magically started working ... so closing this issue now. Never found out what was wrong in the first place
