### ISSUE TITLE
Elements outside of viewport are not captured in chrome.

### ISSUE THREAD

**Issue by pturbin-bfg** [Codeception/VisualCeption#42]
i'm using chromebrowser and webdriver.
but all i've got is screenshot of top of the page...
what am i doing wrong ? :D 
~~and when i'm trying to make a screenshot of specific div. - i'm receiving nothing
http://joxi.ru/E2p9ZoLh9xN0DA~~
ok when i'me scrolling to element and then examine this element - everything is alright... but it'll take a lot of time to scroll every page(

**Comment by pturbin-bfg** [comment]
ok
now i find option that allow to capture full picture at once.... information about it was in your changelog... Oo please add it to your readme

**Comment by buresmi7** [comment]
Readme updated, thanks :)
