### ISSUE TITLE
I can't generate report when I useenvironments in my config file

### ISSUE THREAD

**Issue by michalpotasiakdroptica** [Codeception/VisualCeption#51]
When I use environments in my config file https://codeception.com/docs/07-AdvancedUsage#Environments and try to run tests for more that one environment report didn't generate and I can see in my console only this information:
Trying to store file (/app/tests/tests/_output/vcresult.html)
I can see only an empty file when I use more that one environment.
I try the default template and write own template where I didn't use the failedTests variable.

**Comment by buresmi7** [comment]
Hi, please test it. 
You can test the commit with changes with this in composer.json:
"Codeception/VisualCeption": "git+https://git@github.com:buresmi7/VisualCeption.git#72c225e846746eeee945d2401927084736f8339d",

**Comment by michalpotasiakdroptica** [comment]
I see that the file names have changed but the effect for me is the same report is generated only for one environment when I run several environment files is empty (the same like before fix). It seems to me that it changes to empty when the tests are started on the second environment.

**Comment by buresmi7** [comment]
Please show me command which you run tests

**Comment by michalpotasiakdroptica** [comment]
For example:
docker-console --with-env test 'visual --env desktop --env tablet --env mobile' 
becouse I use docker-console to run tests https://www.droptica.com/blog/start-your-adventure-docker-console-example-drupal-7-project/

**Comment by buresmi7** [comment]
Ok, it is working in commit  c897f4ddc5785b9ddcf7ddbc0ff5f19e3f488d1a
Please try it. After success test, I will merge pull request

**Comment by michalpotasiakdroptica** [comment]
I confirm that it is working now and I have a separate report for each env
