### ISSUE TITLE
fullScreenShot silently disables $excludeElements

### ISSUE THREAD

**Issue by stefanfisk** [Codeception/VisualCeption#57]
When using `fullscreenShot`, `$excludeElements` is not used.

https://github.com/Codeception/VisualCeption/blob/master/module/VisualCeption.php#L382

Moving `hideElementsForScreenshot()`/`resetHideElementsForScreenshot()` to outside the `fullscreenShot` if/else seems to work.

Does anyone know if there's a reason for the current state, or should I just submit a PR?

**Comment by buresmi7** [comment]
Hi, I think it is mistake, so please send PR :)

**Comment by stefanfisk** [comment]
I also found additional bugs with regards to `fullscreenShot` that I personally need fixed (not scrolling to top before iterating downwards, not cropping properly, and maybe something else I can't remember right now), so expect a PR within the coming weeks!

**Comment by MGerasimchuk** [comment]
@buresmi7 hi,
I also faced this issue and prepared MR https://github.com/Codeception/VisualCeption/pull/66 to fix it.
Please see if you have time
