### ISSUE TITLE
Unable to write screenshot on using Windows

### ISSUE THREAD

**Issue by OwnerOfThisIsle** [Codeception/VisualCeption#7]
This has already been reported and fixed, but only in the deprecated repo:

https://github.com/DigitalProducts/codeception-module-visualception/pull/43/commits/95c74dd023cb1bc03876b99e060b874d96d967e6

I had the same issue as described: My TestCases will never fail and a null byte file  called "C" is created instead a partial screenshot.

I tried the fix in my environment and it workes like a charm, so why was it left out in this repo?

**Comment by buresmi7** [comment]
This fork was created before your commit. Unfortunately an information about deprecated repository has been published later. Please create a new pull request with a fix. 

My commit touched lines which you refer: https://github.com/Codeception/VisualCeption/commit/a66f6e05ef654c4e44a1dc8d3336fd5118108217

There is the test signature in format: className:testMethod

I found, that a colon is a reserved character on windows. It would be nice to make a test (unit) for this feature.

**Comment by buresmi7** [comment]
I missed that the fix was commited here: https://github.com/Codeception/VisualCeption/commit/06eaab2711f581ca0f32eb24e0cf0c02ea5bad67#diff-3ed81dac7c06d56fc3b36c5f96ffa2eeR307
